{% set name = "savu-lite" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DiamondLightSource/Savu/archive/py37_local.zip
  sha256: 50f2bbc25bcc37ae0ba26a88d800f42b988de96d07142de4fb5170ac7ffa0ba2

build:
  number: 2
  skip: True # [not linux64 and not py==27]

requirements:
  host:
    - python
    - pip
    - wheel

  run:
    - python=3.7
    - numpy=1.15
    - astra-toolbox
    - cudatoolkit
    - scipy
    - fftw
    - pyfftw
    - hdf5
    - tomobar
    - ccpi-reconstruction
    - ccpi-regulariser
    - larix
    - tomophantom
    - h5py=*=mpi_openmpi*
    - openmpi
    - mpi4py
    - colorama
    - linecache2
    - traceback2
    - pyyaml
    - scikit-image
    - fabio
    - peakutils
    - tifffile
    - nvidia-ml
    - pyfai

test:
  imports:
    - colorama
    - h5py
    - mpi4py
    - numpy
    - scipy
    - pyfftw
    - tomobar    
    - linecache2
    - traceback2
    - savu
    - yaml

  commands:
    - savu --version
    - savu_config -h
    - savu_quick_tests

about:
  home: https://github.com/DiamondLightSource/Savu
  license: Apache V2 and GPL V3
  license_family: GPL3
  doc_url: https://savu-lite.readthedocs.io/en/latest/
  dev_url: https://github.com/alunrobinson/savu-lite
  summary: "Savu-Lite - Minimal version of Savu Tomography Reconstruction and Processing Pipeline"

extra:
  recipe-maintainers:
    - DaniilKazantsev
    - AlunRobinson
